ERM-1540 Support for multiple roles per organisation
folio-org/mod-agreements pull request #417
Opened 2021-05-18 16:16 UTC by CalamityC

* add new domain class, view for SubscriptionAgreementOrgRole
* change domain class, view for SubscriptionAgreementOrg
* update migrations file
* add validation to SubscriptionAgreement
* add error messages

2021-05-19 14:13 UTC, EthanFreestone requested changes

2021-05-19 14:13 UTC, EthanFreestone commented on service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
> +              errors < 'only.one.primary.org'
I think these should be `<<`?

2021-05-19 14:13 UTC, EthanFreestone commented on service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
> +            boolean no_duplicate_orgs = sa_orgs?.unique().size != sa_orgs.size()
This will need to be size()

2021-05-19 14:13 UTC, EthanFreestone commented on service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
> +            return errors.size > 0 ? errors : true
This will also need size()

2021-05-19 14:13 UTC, EthanFreestone commented on service/grails-app/migrations/update-mod-agreements-4-0.groovy
> +          println("transferId: ${transferId}")
These println lines should be removed from migrations once you're happy

2021-05-19 14:19 UTC, CalamityC commented on service/grails-app/domain/org/olf/erm/SubscriptionAgreementOrgRole.groovy
> +  @Defaults(['Content Provider', 'Subscription Agent', 'Vendor'])
yes changed that already.

2021-05-20 09:19 UTC, EthanFreestone commented on service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
> +          orgs(validator: { Collection<SubscriptionAgreementOrg> sa_orgs ->
I don't know if that will solve the issue, but it's a good starting pt

2021-05-21 12:27 UTC, ostephens commented on service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
> +          orgs(validator: { Collection<SubscriptionAgreementOrg> sa_orgs ->
Ethan's suggestion works for me for the primaryCount except there's a missing ' so I think it should be:
```
if (primaryCount > 1) {
    errors.rejectValue('orgs', 'only.one.primary.org')
}
```

2021-05-21 13:14 UTC, ostephens commented on service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
> +            boolean no_duplicate_orgs = sa_orgs?.unique().size() != sa_orgs.size()
This is checking for unique SubscriptionAgreementOrgs rather than whether multiple SubscriptionAgreementOrgs reference the same Org. We could change this to check the `sao.org.id` instead but I think worth us discussing this further (see Slack discussion https://folio-project.slack.com/archives/CAYCU07SN/p1621528345035600)

2021-05-21 16:52 UTC, ostephens commented on service/grails-app/i18n/messages.properties
> +only.one.primary.org=Property {0} of {1} can only have one primary organization
Using the changes to the validator suggested above, this comes through with {0} and {1} as literals. This is the response to a PUT with multiple `primaryOrg=true`
```
{
    "total": 1,
    "errors": [
        {
            "code": "only.one.primary.org",
            "object": "org.olf.erm.SubscriptionAgreement",
            "i18n_code": "org.olf.erm.SubscriptionAgreement.orgs.only.one.primary.org",
            "message": "Property {0} of {1} can only have one primary organization"
        }
    ]
}
```
But I don't think these errors are shown to the user anyway so not sure how much it matters

2021-05-25 12:44 UTC, EthanFreestone commented on service/grails-app/i18n/messages.properties
> +only.one.primary.org=Property {0} of {1} can only have one primary organization
This can be changed just to "Subscription agreements can only have one primary organization"

2021-05-25 12:44 UTC, EthanFreestone commented on service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
> +            boolean no_duplicate_orgs = sa_orgs?.unique().size() != sa_orgs.size()
As above, decision made to remove the duplicate orgs validation and keep just the primary count validation.

2021-05-26 09:29 UTC, EthanFreestone approved these changes

2021-05-26 09:29 UTC, EthanFreestone commented on service/grails-app/domain/org/olf/erm/SubscriptionAgreement.groovy
> +          // it should be validated that the same org is not attached twice to a subscription agreement
Remove this top comment please, since we're holding out on the duplication validation

2021-05-26 09:29 UTC, EthanFreestone commented on service/grails-app/views/subscriptionAgreementOrgRole/_subscriptionAgreementOrgRole.gson
> +json g.render(subscriptionAgreementOrgRole, [expand: ['role', 'note' ]])
I don't believe you need to expand the note here, since it's just a string -- check though

2021-06-18 15:29 UTC, merged