ERM-2045: Extend Package data model to store additional information
folio-org/mod-agreements pull request #545
Opened 2022-04-06 12:31 UTC by peterboehm

2022-04-12 09:36 UTC, EthanFreestone requested changes

2022-04-12 09:36 UTC, EthanFreestone commented on service/grails-app/views/alternateResourceNames/_alternateResourceNames.gson
> +json g.render(alternateResourceName)
I would like these to exclude "owner". We will only ever fetch these from their owner anyway, so it seems unnecessary to return that data.

2022-04-12 09:36 UTC, EthanFreestone commented on service/grails-app/views/packageDescriptionUrl/_packageDescriptionUrl.gson
> +json g.render(packageDescriptionUrl)
I would like these to exclude "owner". We will only ever fetch these from their owner anyway, so it seems unnecessary to return that data.

2022-04-12 09:36 UTC, EthanFreestone commented on service/grails-app/views/contentType/_contentType.gson
> +json g.render(contentType)
I would like these to exclude "owner". We will only ever fetch these from their owner anyway, so it seems unnecessary to return that data.

2022-04-14 15:06 UTC, peterboehm commented on service/grails-app/views/alternateResourceNames/_alternateResourceNames.gson
> +json g.render(alternateResourceName, [excludes: ['owner']])
this seems to be ignored while working on the other two

2022-04-14 15:07 UTC, peterboehm commented
I pushed changes to exclude the owner on the JSON, but the exclude seems to be ignored on alternateResourceName, see comment above

2022-05-03 13:28 UTC, peterboehm commented on service/grails-app/domain/org/olf/kb/ContentType.groovy
> +  String contentType
Changed to RefData with values "Serials", "Monographs", "Databases"

2022-05-03 13:28 UTC, peterboehm commented on service/grails-app/views/packageDescriptionUrl/_packageDescriptionUrl.gson
> +json g.render(packageDescriptionUrl)
done

2022-05-03 13:28 UTC, peterboehm commented on service/grails-app/views/contentType/_contentType.gson
> +json g.render(contentType)
done

2022-05-03 13:30 UTC, peterboehm commented on service/grails-app/views/alternateResourceNames/_alternateResourceNames.gson
> +json g.render(alternateResourceName)
exclude on 'owner' still doesn't work

2022-05-03 13:31 UTC, peterboehm commented
Excluding 'owner' on 'alternateResourceNames' still doesn't work after change to ermResource.gson as discussed today

2022-05-06 14:17 UTC, merged